#pragma once

#include <mysql/jdbc.h>
#include <string>
#include <vector>

/**
 * @class DataStore
 * @brief SQL abstraction layer that wraps the MySQL Connector/C++ JDBC API.
 *
 * All domain modules hold a reference to a single DataStore instance.
 * Results are returned as vector<vector<string>> so that DataStore remains
 * free of domain knowledge; callers convert strings to typed fields as needed.
 *
 * Connection credentials are read from Config.h constants at connect() time.
 */
class DataStore {
public:
    /**
     * @brief Initialises the JDBC driver and opens a connection to the database.
     *
     * Reads DB_HOST, DB_PORT, DB_NAME, DB_USER, and DB_PASS from Config.h.
     * Logs a descriptive error to std::cerr on failure.
     *
     * @return true  if the connection was established successfully.
     * @return false if the driver or connection could not be created.
     */
    bool connect();

    /**
     * @brief Closes the active connection and frees the connection object.
     *
     * Safe to call even if connect() was never called or already failed.
     * After disconnect(), conn is set to nullptr.
     */
    void disconnect();

    /**
     * @brief Executes a plain (non-parameterised) SELECT-style SQL statement.
     *
     * Intended for read-only queries that do not require parameter binding.
     * Logs the exception message to std::cerr on failure.
     *
     * @param sql  The SQL query string to execute.
     * @return     A vector of rows, where each row is a vector of column values
     *             encoded as strings. Returns an empty vector on error or when
     *             the result set is empty.
     */
    std::vector<std::vector<std::string>> executeQuery(const std::string& sql);

    /**
     * @brief Executes a plain (non-parameterised) DML SQL statement.
     *
     * Intended for INSERT, UPDATE, or DELETE statements that do not require
     * parameter binding. Logs the exception message to std::cerr on failure.
     *
     * @param sql  The SQL statement string to execute.
     * @return     The number of rows affected by the statement, or -1 on error.
     */
    int executeUpdate(const std::string& sql);

    /**
     * @brief Executes a parameterised SELECT-style SQL statement.
     *
     * Uses PreparedStatement to safely bind the supplied parameters,
     * preventing SQL injection. Each element of @p params is bound as a string.
     *
     * @param sql     The SQL query string containing '?' placeholders.
     * @param params  String-encoded values to bind to each '?' in order.
     * @return        A vector of rows (each row a vector of column strings).
     *                Returns an empty vector on error or empty result set.
     */
    std::vector<std::vector<std::string>> preparedQuery(
        const std::string& sql,
        const std::vector<std::string>& params);

    /**
     * @brief Executes a parameterised DML SQL statement.
     *
     * Uses PreparedStatement to safely bind the supplied parameters,
     * preventing SQL injection. Each element of @p params is bound as a string.
     * After a successful INSERT, the generated AUTO_INCREMENT id is cached and
     * retrievable via getLastInsertId().
     *
     * @param sql     The SQL statement string containing '?' placeholders.
     * @param params  String-encoded values to bind to each '?' in order.
     * @return        The number of rows affected by the statement, or -1 on error.
     */
    int preparedUpdate(
        const std::string& sql,
        const std::vector<std::string>& params);

    /**
     * @brief Returns the AUTO_INCREMENT id generated by the most recent INSERT.
     *
     * Should be called immediately after a successful preparedUpdate() or
     * executeUpdate() that performed an INSERT on a table with an
     * AUTO_INCREMENT primary key.
     *
     * @return The last inserted row id, or 0 if no INSERT has been performed.
     */
    int getLastInsertId();

private:
    /// JDBC driver instance (singleton managed by the connector library).
    sql::mysql::MySQL_Driver* driver = nullptr;

    /// Active JDBC connection. nullptr when disconnected.
    sql::Connection* conn = nullptr;

    /// Cached id from the most recent INSERT statement.
    int lastInsertId = 0;
};
